// <auto-generated />
using Exodus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Exodus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324110000_DropLegacyStockColumn")]
    partial class DropLegacyStockColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
