// <auto-generated />
using Exodus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Exodus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226000001_AddOrderNumberAndMissingOrderFields")]
    partial class AddOrderNumberAndMissingOrderFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
